swagger: "2.0"
info:
  version: "0.0.1"
  title: Starships Collection
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /starships:
    x-swagger-router-controller: starships
    get:
      operationId: getStarships
      summary: Get all starships
      description: get starships list
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetStarshipsListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: saveStarship
      summary: add new starship
      description: add a new starship to the list
      # movie info to be stored
      parameters:
        - name: model
          description: Starship properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Starship"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  
  /starships/{id}:
    x-swagger-router-controller: starships
    # our controller name
    get:
      operationId: getStarship
      description: get a starship
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Starship"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"          
    put:
      operationId: updateStarship
      description: update a starship
      # define the parameters
      parameters:
        - name: id
          description: Starship id
          type: string
          in: path
          required: true
        - name: model
          description: Starship properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Starship"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"   
    delete:
      operationId: deleteStarship
      description: delete a starship
      # define the parameters
      parameters:
        - name: id
          description: Starship id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
  
  /films:
    x-swagger-router-controller: films
    get:
      operationId: getFilms
      summary: Get all films
      description: get films list
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetFilmsListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: saveFilm
      summary: add new film
      description: add a new film to the list
      # movie info to be stored
      parameters:
        - name: model
          description: Starship properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Film"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"     
            
  /films/{id}:
    x-swagger-router-controller: films
    # our controller name
    get:
      operationId: getFilm
      description: get a film
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Film"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"                      
    put:
      operationId: updateFilm
      description: update a film
      # define the parameters
      parameters:
        - name: id
          description: Film id
          type: string
          in: path
          required: true
        - name: model
          description: Film properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Film"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"               
            
  /seeds:
    x-swagger-router-controller: seeds
    get:
      operationId: populate
      summary: populate db
      description: populate all db
      responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/GeneralResponse"
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"     
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
 # ---------------------------------------------------------#
 # ---------------------------------------------------------#
 # General Responses
 # ---------------------------------------------------------#
 # ---------------------------------------------------------#       
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GeneralResponse:
      type: object
      properties:
        success:
          type: number
          description: returns 1 if successful
        description:
          type: string
          description: a short comment 
      required:
        - success
        - description        
 # ---------------------------------------------------------#
 # ---------------------------------------------------------#
 # models      
 # ---------------------------------------------------------#
 # ---------------------------------------------------------#
  Starship:        
    description: A Starship
    type: object
    title: Starship
    required:
    - name
    - model
    - manufacturer
    - cost_in_credits
    - length
    - max_atmosphering_speed
    - crew
    - passengers
    - cargo_capacity
    - consumables
    - hyperdrive_rating
    - MGLT
    - starship_class
    - url
    properties:        
      hyperdrive_rating:
        type: string
        description: The class of this starships hyperdrive.
      MGLT:
        type: string
        description: The Maximum number of Megalights this starship can travel in a standard
          hour. A Megalight is a standard unit of distance and has never been defined
          before within the Star Wars universe. This figure is only really useful for
          measuring the difference in speed of starships. We can assume it is similar
          to AU, the distance between our Sun (Sol) and Earth.
      model:
        type: string
        description: The model or official name of this starship. Such as T-65 X-wing
          or DS-1 Orbital Battle Station.
      cargo_capacity:
        type: string
        description: The maximum number of kilograms that this starship can transport.
      max_atmosphering_speed:
        type: string
        description: The maximum speed of this starship in atmosphere. n/a if this starship
          is incapable of atmosphering flight.
      crew:
        type: string
        description: The number of personnel needed to run or pilot this starship.
      consumables:
        type: string
        description: The maximum length of time that this starship can provide consumables
          for its entire crew without having to resupply.
      manufacturer:
        type: string
        description: The manufacturer of this starship. Comma seperated if more than one.
      url:
        type: string
        description: The hypermedia URL of this resource.
        format: uri
      passengers:
        type: string
        description: The number of non-essential people this starship can transport.
      length:
        type: string
        description: The length of this starship in meters.
      starship_class:
        type: string
        description: The class of this starship, such as Starfighter or Deep Space Mobile
          Battlestation.
      name:
        type: string
        description: The name of this starship. The common name, such as Death Star.
      cost_in_credits:
        type: string
        description: The cost of this starship new, in galactic credits.
      films:
          type: array
          items: 
            type: integer
 # ---------------------------------------------------------#
 # Film      
 # ---------------------------------------------------------#
  Film:        
    description: A Film
    type: object
    title: Film
    required:
    - title
    - episode_id
    - opening_crawl
    - director
    - producer
    - release_date
    - url
    properties:        
      episode_id:
        type: integer
        description: The episode number of this film.
      director:
        type: string
        description: The director of this film.
      opening_crawl:
        type: string
        description: The opening crawl text at the beginning of this film.
      title:
        type: string
        description: The title of this film.
      release_date:
        type: string
        description: The release date at original creator country.
        format: date
      url:
        type: string
        description: The url of this resource
        format: uri
      producer:
        type: string
        description: The producer(s) of this film.
      starships:
          type: array
          items: 
            type: integer
 # ---------------------------------------------------------#
 # models responses
 # ---------------------------------------------------------#     
        
  GetStarshipsListResponse:
      required:
        - starships
      properties:
        # The array of sharship
        starships:
          type: array
          items: 
            $ref: '#/definitions/Starship'
  GetFilmsListResponse:
      required:
        - films
      properties:
        # The array of sharship
        films:
          type: array
          items: 
            $ref: '#/definitions/Film'            