environment: prod
api:
  port: null
db:
  username: acjpbhfnsnlmqt
  password: d8dc387b9fed87d36af61a21fb7b7363da0bd7e9c1a6dd924cb4dba5811ffc7e
  database: dffih14ufbpr6u
  host: ec2-50-19-105-113.compute-1.amazonaws.com
  port: 5432
  dialect: postgres
  wipe: true
  logging: false
  ssl: true
  dialectOptions: {
    ssl: true
  }