environment: local
api:
  port: 10010
db:  
  username: rcarvalhoxavier
  password: 
  database: rcarvalhoxavier
  host: 127.0.0.1
  port: 5432
  dialect: postgres
  wipe: false
  logging: false
  dialectOptions: {
    ssl: false
  }